---

- hosts: 'webservers'
  remote_user: 'root'
  tasks:
    - name: 'Install apache2'
      apt:
       name: 'apache2'
       state: 'present'
       update_cache: 'yes'
      become: true 

    - name: 'Install mysql-server'   
      apt: 
        name: 'mysql-server'
        update_cache: 'yes' 
        cache_valid_time: 3600
        state: 'present'
      become: true

    - name: 'Install php and modules'
      apt:
        update_cache: true
        name:
          - php
          - php-mysql
          - php-fpm
          - php-zip
          - python3-mysqldb
          - php-common
          - php-mbstring
          - php-gd
          - php-intl 
          - php-xml 
          - php-mysql
          - libapache2-mod-php
      become: true

    - name: 'Download and exract Wordpress files'
      unarchive: 
        src: 'https://wordpress.org/latest.tar.gz'
        dest: '/var/www/html/'
        remote_src: true
        owner: 'www-data'
        group: 'www-data' 
      become: true

    - name: 'Set mysql root user password'
      mysql_user:
        login_user: 'root'
        login_password: '123456'
        name: 'root'
        password: '123456' 
      become: true
  

    - name: 'Create WP mysql user'
      community.mysql.mysql_user:
        name: 'wpuser'
        password: 'wp-123456!!!'
        priv: '*.*:ALL'
        login_user: 'root'
        login_password: '123456'
        state: 'present'
      become: true

    - name: 'Create a new database called wordpress'
      mysql_db:
        login_password: '123456'
        login_user: 'root'
        name: 'wordpress'
        state: 'present'


    - name: 'Upload wp-config.php'
      copy: 
        src: 'wp-config.php'
        dest: '/var/www/html/wordpress/wp-config.php'
        owner: 'www-data'
        group: 'www-data'
      become: true  
    
    - name: 'change apache default config file'
      copy:
        src: '000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: 'true'


