---

- hosts: 'webservers'
  remote_user: 'ubuntu'
  tasks:
    - name: 'Install nginx'
      apt:
       name: 'nginx'
       state: 'present'
      become: true 

    - name: 'Install mysql-server'   
      apt: 
        name: 'mysql-server'
        update_cache: 'yes' 
        cache_valid_time: 3600
        state: 'present'
      become: true

    - name: 'Install php and modules'
      apt:
        update_cache: true
        name:
          - php
          - php-mysql
          - php-fpm
          - php-zip
          - python3-mysqldb
      become: true

    - name: 'Download and exract Wordpress files'
      unarchive: 
        src: 'https://wordpress.org/latest.tar.gz'
        dest: '/opt'
        remote_src: true 
      become: true
      
    - name: 'Set mysql root user password'
      mysql_user:
        login_user: 'root'
        login_password: '123456'
        name: 'root'
        password: '123456' 
      become: true

    - name: 'Create WP mysql user'
      community.mysql.mysql_user:
        name: 'wpuser'
        password: 'wp-123456!!!'
        priv: '*.*:ALL'
        login_user: 'root'
        login_password: '123456'
        state: 'present'
      become: true

    - name: 'Create a new database called wordpress'
      mysql_db:
        login_password: '123456'
        login_user: 'root'
        name: 'wordpress'
        state: 'present'

    - name: 'Configure new MySQL user called wpuser'
      mysql_user:
        login_user: 'root'
        login_password: '123456'
        name: 'wpuser'
        password: 'wp_user123456!!!'
        priv: 'wordpress.*:ALL'

    - name: 'Upload wp-config.php'
      copy: 
        src: 'wp-config.php'
        dest: '/opt/wordpress/wp-config.php'
      become: true  
