---

- hosts: 'webservers'
  remote_user: 'root'
  tasks:
    - name: 'Install nginx'
      apt:
       name: 'nginx'
       state: 'present'
      become: true 
    - name: 'Install mysql-server'   
      apt: 
        name: 'mysql-server'
        update_cache: 'yes' 
        cache_valid_time: 3600
        state: 'present'
      become: true
    - name: 'Install php and modules'
      apt:
        update_cache: true
        name: 
          - php
          - php-mysql 
          - php-fpm
          - php-zip
    - name: 'Install python requirements for mySQL'
      pip:
        name: 'PyMySQL'
        state: 'present'        
    - name: 'Dowoload Wordpress'
      unarchive:
        src: 'https://wordpress.org/latest.tar.gz'
        dest: '/opt'
        remote_src: true
      become: true  
    - name: 'Set mysql root password'
      mysql_user: 
        name: 'root'
        password: '123456'
        login_user: 'root'
        login_password: ''
        login_unix_socket: '/var/run/mysqld/mysql.sock'
        check_implicit_admin: yes
        priv: '*.*:ALL'
      become: true 
    - name: 'Create database for wordpress'
      community.mysql.mysql_user: 
         name: 'wordpress_user'
         password: '123456'
         priv: '*.*:ALL'
         login_password: '123456'
         login_user: 'root'
